### ISSUE TITLE
AttributeError: module 'config' has no attribute 'reddit_id'

### ISSUE THREAD

**Issue by JakeScervino** [zachhuang610/wsb_scraper#1]
I am trying to run the python script and I keep getting this error `AttributeError: module 'config' has no attribute 'reddit_id'`.

**Comment by zachhuang610** [comment]
Yeah so the script relies on a couple of APIs where you need essentially a user id and password. I can't share mine publicly for security reasons so I put them in a config file. To run the script on your machine, you'll need to get the following:

Reddit: secret and id from reddit API
Discord: bot token and channel id
Robinhood: account username and password

lmk if you need any followup info.

**Comment by JakeScervino** [comment]
Hi, thanks for your reply. I apologize if these are stupid questions, but I have never used python or tried running a python script before. How do I get my Reddit secret and id? Also, I don't have Robinhood or Discord.

**Comment by zachhuang610** [comment]
All good! To get a reddit secret and id I suggest you follow this [link](https://www.storybench.org/how-to-scrape-reddit-with-python/). You only need to follow the steps up to the part in the tutorial where coding begins. If you don't have robinhood or discord, I suggest you use an older commit of this project, probably this [one](https://github.com/zachhuang610/wsb_scraper/tree/c0e5959afd5d9400b13a312b2c58887f87272e31).

**Comment by JakeScervino** [comment]
I added my Reddit id and secret to the main.py file:
`reddit = praw.Reddit(
        client_id='0EI0vtGixluFBw',
        client_secret='a9wKuGBrlwwT4_kelYvbbdt3EXJ9KA',
        user_agent="WSB Scraping",
    )`
However, now the command prompt doesn't return anything when I run "python main.py".

**Comment by zachhuang610** [comment]
In the output folder you should see 4 txt files. where output is stored
